### ISSUE TITLE
Problems using the project

### ISSUE THREAD

**Issue by knowpwr** [kwsch/FlatCrawler#2]
Hello. I have attempted to use the project with the following file:

https://www.mediafire.com/file/mt04qhvv17a3ic7/test.bin/file

Though, it does not show any structure at all. Does the project require something to do in order for it to work?

Thanks for your time.

**Comment by kwsch** [comment]
The program is a command line crawler; once the program is run, you tell it what to do.

At the moment, the commands it supports aren't documented outside of the source code. If you want to see where it is processing commands, [see here](https://github.com/kwsch/FlatCrawler/blob/3043e3fa3f7a199cc39ca8f5dfe34e1cd047a588/FlatCrawler.ConsoleApp/Crawler/ConsoleCrawler.cs#L58).

Upon starting the program, we see it ask for us to open a file. So I tell it which file:
![image](https://user-images.githubusercontent.com/6393368/189918239-bf820d33-7951-4e47-9dd0-73cea267a6e1.png)

After entering some commands to try and interpret data at certain nodes, some of the structure becomes apparent:
![image](https://user-images.githubusercontent.com/6393368/189920553-0f040bb5-dd1f-48b6-98a5-70757187d937.png)

The program does not make guesses as to the data structure. It's up to you to try certain field types and progressively document what each field is.

**Comment by knowpwr** [comment]
Thanks a lot for the information and for examining my file. It is much appreciated. It would be really great if you provide a guide on how to use the commands. This project is unique. There is nothing like it out there and the demand for a tool to reverse engineer FlatBuffers binary files is high. Also, if it is not too much to ask, can you explain the representation above. I am not quite sure what I am looking at. Also, is the structure in the image above exact, or it is just prediction? Lastly, I have a suggestion, if it is possible, can you offer the option to generate JSON as output.

**Comment by kwsch** [comment]
I've added a wiki to describe how the program works, and a basic explanation of each command that can be entered.

https://github.com/kwsch/FlatCrawler/wiki/Commands-How-To

This program does not automatically reverse & validate a schema due to multiple interchangeable field types being valid in certain scenarios (a float is 32bit, same as an integer). It is up to the reverse-engineer to guess & check on their own; it would be a pretty big effort (logically and computationally) to guess (bruteforce) every single possible arrangement and validate the deserialized data serializes back to the input file. Plus there's so many hard-to-handle cases like unions, and inline structs that aren't currently handled by the program.

Once you have transcribed a fbs that you believe represents the serialized data, you can run the flatc compiler to try and dump json (bin+fbs->json) via flatc's command line.

**Comment by knowpwr** [comment]
@kwsch Thanks for the wiki. Though, a use case would actually do wonders. You can offer a binary flatbuffers file and use your tool to show the reversing the process. This would actually make your repo very popular. There is not much reverse FB engineering resources out there. Anyway, it is just a thought.

Regards and thanks for your time.
